# Generated by Django 3.0.7 on 2020-09-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_contactus_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('serialno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=264)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=264)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
